version: "3.3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3305:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: